# Generated by Django 5.2.7 on 2025-10-27 08:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=256, unique=True)),
                ('brand', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('card_type', models.CharField(max_length=150)),
                ('upload_image', models.JSONField(blank=True, default=list)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('status', models.CharField(choices=[('unused', 'Unused'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('invalid', 'Invalid'), ('valid', 'Valid')], default='unused', max_length=20)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_giftcard', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
